# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CD <- function(node, dataSize, data, nlevels, obsIndex_R, eor_nr, eor, lambda_seq, nlam, eps, convLb, qtol, weights, gamma, upperbound) {
    .Call('discretecdAlgorithm_CD', PACKAGE = 'discretecdAlgorithm', node, dataSize, data, nlevels, obsIndex_R, eor_nr, eor, lambda_seq, nlam, eps, convLb, qtol, weights, gamma, upperbound)
}

lambdaMax <- function(node, dataSize, data, nlevels, obsIndex_R, weights, gamma, upperbound) {
    .Call('discretecdAlgorithm_lambdaMax', PACKAGE = 'discretecdAlgorithm', node, dataSize, data, nlevels, obsIndex_R, weights, gamma, upperbound)
}

