# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CD <- function(node, dataSize, data, nlevels, obsIndex_R, eor_nr, eor, lambda_seq, nlam, eps, convLb, qtol, weights, gamma, upperbound, threshold) {
    .Call('discretecdAlgorithm_CD', PACKAGE = 'discretecdAlgorithm', node, dataSize, data, nlevels, obsIndex_R, eor_nr, eor, lambda_seq, nlam, eps, convLb, qtol, weights, gamma, upperbound, threshold)
}

lambdaMax <- function(node, dataSize, data, nlevels, obsIndex_R, weights, gamma, upperbound) {
    .Call('discretecdAlgorithm_lambdaMax', PACKAGE = 'discretecdAlgorithm', node, dataSize, data, nlevels, obsIndex_R, weights, gamma, upperbound)
}

DatGen <- function(maxdeg, node, ordex, ts, dataSize, ivn, ivn_vals, ivn_rand, coef_length, nlevels, coef) {
    .Call('discretecdAlgorithm_DatGen', PACKAGE = 'discretecdAlgorithm', maxdeg, node, ordex, ts, dataSize, ivn, ivn_vals, ivn_rand, coef_length, nlevels, coef)
}

